[package]
name = "staticdir"
version = "0.1.0"
authors = ["franza <nico.franza@gmail.com>"]

[dependencies.iron]
version = "*"

[dependencies]
rustc-serialize = "0.3"


[dev-dependencies.hyper]
version = "*"

[dev-dependencies.mount]
git = "https://github.com/iron/mount.git"

[dev-dependencies]
staticfile = "*"
